version: "3.8"

services:
  trading-bot:
    build: .
    container_name: coin-gemini-bot
    restart: unless-stopped

    # Environment variables
    environment:
      - TRADE_AMOUNT_USDT=${TRADE_AMOUNT_USDT:-15.0}
      - RISK_REWARD_RATIO=${RISK_REWARD_RATIO:-1.5}
      - MIN_USDT_BALANCE=${MIN_USDT_BALANCE:-50.0}
      - USE_TESTNET=${USE_TESTNET:-True}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}

    # Use .env file for sensitive data
    env_file:
      - .env

    # Volumes for persistent data
    volumes:
      - ./active_trades.txt:/app/active_trades.txt
      - ./watchlist.txt:/app/watchlist.txt:ro

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

    # Health check
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python -c 'import sys; print(\"Bot is healthy\"); sys.exit(0)' || exit 1",
        ]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 1m

  # Optional: Monitoring service
  # Uncomment if you want to add monitoring
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=3600
  #   depends_on:
  #     - trading-bot

volumes:
  data:
  logs:
