name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        ⚠️ **Important**: This is an AI-generated trading bot (90%). Please ensure you've tested with testnet first.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Are you using testnet or live trading?
      options:
        - Testnet (recommended for testing)
        - Live trading (production)
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Start the bot with './start.sh start'
        2. Check logs with './start.sh logs'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output (remove any API keys!)
      render: shell

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the trading bot are you running?
      options:
        - Latest (main branch)
        - v2.0.0
        - v1.0.0
        - Other (specify in description)
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our safety guidelines
      options:
        - label: I have tested this with testnet first (if applicable)
          required: true
        - label: I have removed any API keys or sensitive data from logs
          required: true
        - label: I understand this is educational software and trading involves risk
          required: true
